-- Active: 1691348411366@@127.0.0.1@3306


CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT('NORMAL') NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, 
	created_at TEXT DEFAULT(DATETIME()) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments_posts (
	id TEXT PRIMARY KEY NOT NULL,
	postId TEXT NOT NULL,
	parent_comment_id TEXT NULL DEFAULT(NULL),
	content TEXT NOT NULL,
	like INTEGER DEFAULT(0) NOT NULL,
	dislike INTEGER DEFAULT(0) NOT NULL,
	created_at TEXT DEFAULT(DATETIME()) NOT NULL,
	updated_at TEXT DEFAULT(DATETIME()) NOT NULL,
	FOREIGN KEY(postId) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(parent_comment_id) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS posts (
id TEXT PRIMARY KEY NOT NULL,
content TEXT NOT NULL,
like INTEGER DEFAULT(0) NOT NULL,
dislike INTEGER DEFAULT(0) NOT NULL,
amount_comments INTEGER DEFAULT(0) NOT NULL,
created_at TEXT DEFAULT(DATETIME()) NOT NULL,
updated_at TEXT DEFAULT(DATETIME()) NOT NULL
);


DROP TABLE IF EXISTS users;