-- Active: 1691348411366@@127.0.0.1@3306

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    role TEXT DEFAULT('NORMAL') NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL, 
	created_at TEXT DEFAULT(DATETIME()) NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
id TEXT PRIMARY KEY NOT NULL,
user_id TEXT NOT NULL,
name_user TEXT NOT NULL,
content TEXT NOT NULL,
like INTEGER DEFAULT(0) NOT NULL,
dislike INTEGER DEFAULT(0) NOT NULL,
created_at TEXT DEFAULT(DATETIME()) NOT NULL,
updated_at TEXT DEFAULT(DATETIME()) NOT NULL,
FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
	id TEXT PRIMARY KEY NOT NULL,
	post_id TEXT NOT NULL,
	parent_comment_id TEXT NULL DEFAULT(NULL),
	content TEXT NOT NULL,
	id_user TEXT NOT NULL,
	like INTEGER DEFAULT(0) NOT NULL,
	dislike INTEGER DEFAULT(0) NOT NULL,
	amount_comment INTEGER DEFAULT(0) NOT NULL,
	created_at TEXT DEFAULT(DATETIME()) NOT NULL,
	updated_at TEXT DEFAULT(DATETIME()) NOT NULL,
	FOREIGN KEY(post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(parent_comment_id) REFERENCES comments_posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(id_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE
    IF NOT EXISTS likes_dislikes_posts (
        user_id TEXT NOT NULL,
        post_id TEXT NOT NULL,
        like INTEGER NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY(post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE
    );
	
CREATE TABLE
    IF NOT EXISTS likes_dislikes_comments (
        user_id TEXT NOT NULL,
        comment_id TEXT NOT NULL,
        like INTEGER NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
        FOREIGN KEY(comment_id) REFERENCES comments(id) ON UPDATE CASCADE ON DELETE CASCADE
    );


DROP TABLE IF EXISTS comments_posts;